services:
  db:
    image: postgres:14.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-metal_prices_db}
      - POSTGRES_USER=${POSTGRES_USER:-metal_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-metal_password}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-metal_user} -d ${POSTGRES_DB:-metal_prices_db}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:

      - internal
  web:
    build: .
    container_name: metal-info-backend
    command: sh -c "python src/manage.py migrate && python src/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-metal_user}:${POSTGRES_PASSWORD:-metal_password}@db:5432/${POSTGRES_DB:-metal_prices_db}
    networks:
      - internal

  ngrok:
    image: ngrok/ngrok:latest
    container_name: metal-info-backend-ngrok
    # ports:
    #   - "80:80"
    environment:
      - NGROK_AUTHTOKEN=$NGROK_AUTHTOKEN
    command: http --url=$NGROK_URL metal-info-backend:8000
    networks:
      - internal

volumes:
  postgres_data:

networks:
  internal:
    driver: bridge